### ISSUE TITLE
Is there a way to change the drawerLabel of a DrawerComponent dinamically?

### ISSUE THREAD

**Issue by hromacho** [react-navigation/react-navigation-drawer#17]
Hello,
I want to internationalize my app and change its language within it. While all the regular views are updated perfectly at runtime, the drawer does not seem to do so. I've tried several things, like forcing an update of the Root Component of the app, but it does not seem to work either, which really bugs me. 

My guess is that the routeConfig is created at the start of the app statically, and therefore cannot be changed afaik.

Here's a sample of a route of the createDrawerNavigator:

`const DrawerNavigation = createDrawerNavigator({
  Home: {
    screen: StackHome,
    navigationOptions: {
      drawerLabel: I18n.t('home'), //HERE COMES THE TRANSLATED LABEL
      drawerIcon: ({ tintColor }) => (
        <Image style={styles.icon}
          source={require('../../../assets/icons/inicio.png')}
        />
    )},
  },`

I'm using the react-native-i18n library if that means anything.
I've been 2 days already trying to solve this issue, but I can't find anything.
Thanks in advance.

**Comment by hromacho** [comment]
I managed to get this to work by creating my own customDrawerComponent as stated [here:](https://reactnavigation.org/docs/en/drawer-navigator.html#providing-a-custom-contentcomponent)
Instead of a const component, I put it as a class, so I could change its content at runtime (it gets its own lifecycle, you know).

After that, I just had to override the `items` option with an array in the component state. 
`<DrawerItems {...this.props} items={this.state.elements}`. So now, everytime I do a `this.setState({elements: newArrayWithNewLanguage})` it updates in the drawer.

I hope it helps anyone. Closing.

**Comment by nahidmbstu** [comment]
There is a more easy solution for this .  just do it like this ...

 ```
navigationOptions: () =>({
        drawerLabel: I18n.t("Profile"),
        drawerIcon: () => (
          <Icon
            name="user"
            style={{ fontSize: 20, color: "#2b8a3e" }}
            type="SimpleLineIcons"
          />
        )
      })
```
