### ISSUE TITLE
Close drawer when current scene is tapped

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation-drawer#20]
https://github.com/react-navigation/react-navigation/issues/4821

**Comment by rborn** [comment]
@brentvatne  @eriveltonelias not sure https://github.com/react-navigation/react-navigation/issues/5079 is the same issue.

**Comment by eriveltonelias** [comment]
I just tested it on `react-navigation@3.5.1` is working as expected. 

https://snack.expo.io/@eriveltonelias/basic-drawer-config

**Comment by NightWarrior** [comment]
I'm having this issue again, drawer isnt closing on pressing the same screen button after I updated to `react-native` 0.59.5. It was working just fine on `react-native` 0.58.6. (currently using `react-navigation` 3.7.1)

**Comment by eriveltonelias** [comment]
hi @NightWarrior,
try to update to the last of `react-navigation` ( currently is 3.9.1 ), if doesn't work, please open a new issue following the issue template, please.
