### ISSUE TITLE
drawerPosition: "right" appears on the left side on ios when the app is in RTL mode

### ISSUE THREAD

**Issue by 0xori** [react-navigation/react-navigation-drawer#29]
I'm using ` drawerPosition: "right"` in RTL mode. On iOS, the drawer is open on the left side while on Android it works as expected.

I'm currently working around it by doing ` drawerPosition: Platform.OS === "ios" ? "left" : "right"`.
Any Ideas how to solve it more elegantly?

**Comment by kokoapps** [comment]
Im also seeing this. any updates ?

**Comment by brentvatne** [comment]
you'll need to specify a version and provide a repro. there was an issue with rtl + drawer in react-navigation 3 but it was resolved in 3.0.2. create a new issue with more info including a reproducible example please :)

**Comment by elirangoshen** [comment]
please reopen it, as i just updated to the latest version 3.8.1 and it didn't work, i had to make the workaround of adding drawerPosition based on the rtl mode as well. 
btw both  n android and ios.
