### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by tonmanayo** [react-navigation/react-navigation-drawer#31]
Please can we have an option to push the screen when the drawer opens or closes, like most native apps do.
They don't just overlay a screen when a side modal they push the screen over

**Comment by MoudiZd** [comment]
Have you tried the property `drawerType`
Like this :
`drawerType:"front"` 
It seems what you ask about or i am wrong 🤔

**Comment by MoudiZd** [comment]
Have you tried the property `drawerType`
Like this :
`drawerType:"front"` 

Take look into it here 
[https://reactnavigation.org/docs/en/drawer-navigator.html#drawernavigatorconfig]()

It seems what you ask about or i am wrong 🤔

**Comment by tonmanayo** [comment]
@MoudiZd It seems like this was added in react-navigation v3 :D
