### ISSUE TITLE
swipe to back inside drawer

### ISSUE THREAD

**Issue by diego-lipinski-de-castro** [react-navigation/react-navigation-drawer#45]
Is there anyway to enable swipe to go back inside a drawer navigation? I wrapped my app around a drawer navigation and in just one screen I want that when i swipe from left to right it goes back, thats how most apps work on iOS, but i couldnt figure out how to do that, btw i know i can change drawerLockMode to lock the drawer from opening, but I wasnt able to go back on swipe yet

**Comment by eriveltonelias** [comment]
Hi @diego-lipinski-de-castro, 

you can do this https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-drawer-has-a-stack-inside-of-it-and-you-want-to-lock-the-drawer-on-certain-screens
