### ISSUE TITLE
left and right drawer 

### ISSUE THREAD

**Issue by bemazo** [react-navigation/react-navigation-drawer#8]
I have added one left and one right drawer to my app, please see here a test snippet:

https://snack.expo.io/Bkd0MKqb7

If i toogle the drawers by the custom function everything works fine, thanks to @brentvatne for
his example.

Now I open the drawers through the swipe geasture, if I open the right everything is ok.
If I do the same with the left one, the right right swiper will open too after the left one is
complete opened. Seems to be a onComplete or onFinish event?

Thanks for your help,
Ben

**Comment by hungdev** [comment]
+1

**Comment by hamzahayat** [comment]
+1

**Comment by brentvatne** [comment]
this is resolved for react-navigation v3, you can install react-navigation-drawer@1.0.0-alpha.2 to fix it. see https://snack.expo.io/@notbrent/react-navigation-multiple-drawers for an example
